name: Pull ProtonVPN Server Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

jobs:
  pull-protonvpn-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Fetch ProtonVPN server data and create CSV
        shell: pwsh
        run: |
          # Define the URL
          $jsonUrl = "https://api.protonmail.ch/vpn/logicals"

          # Fetch the JSON data from the URL
          $jsonData = Invoke-RestMethod -Uri $jsonUrl -ContentType "application/json"

          # Initialize an array to hold the CSV data
          $csvObjects = @()

          # Iterate over each 'LogicalServer' in the JSON data
          foreach ($logicalServer in $jsonData.LogicalServers) {
              $city = $logicalServer.City
              $exitCountry = $logicalServer.ExitCountry
              # Iterate over each 'Server' in the 'Servers' array
              foreach ($server in $logicalServer.Servers) {
                  # Convert ServicesDown to boolean
                  $servicesDownBool = $server.ServicesDown -eq 1

                  # Create a custom object for each server with the desired properties
                  $csvObjects += [PSCustomObject]@{
                      ExitIP = $server.ExitIP
                      ServicesDown = $servicesDownBool
                      City = $city
                      ExitCountry = $exitCountry
                  }
              }
          }

          # Convert the array of CSV objects to CSV format
          $csvData = $csvObjects | ConvertTo-Csv -NoTypeInformation

          # Define the path for the CSV file
          $csvPath = "${{ github.workspace }}/vpn_servers_info.csv"

          # Save the CSV data to a file
          $csvData | Out-File -FilePath $csvPath

          # Output the path to the CSV file
          Write-Host "CSV file created at: $csvPath"

      - name: Commit updated CSV to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update VPN server data CSV
