name: Pull external data source Sentinel prices

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  pull-sentinel-prices:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Fetch Sentinel Prices data and create CSV
        shell: pwsh
        run: |
          $apiUrl = "https://prices.azure.com/api/retail/prices?currencyCode=GBP&`$filter=productName eq 'Sentinel' and (location eq 'UK South' or location eq 'UK West')"
          $response = Invoke-RestMethod -Uri $apiUrl -Method Get
          $items = $response.Items
          $sortedItems = $items | Sort-Object location, skuName
          $selectedItems = $sortedItems | Select-Object currencyCode, tierMinimumUnits, retailPrice, unitPrice, armRegionName, location, effectiveStartDate, meterId, meterName, productId, skuId, productName, skuName, serviceName, serviceId, serviceFamily, unitOfMeasure, type, isPrimaryMeterRegion, armSkuName
          
          $csvFilePath = "UKSentinelPrices.csv"
          
          if (-not (Test-Path -Path "${{ github.workspace }}/ExternalData/")) { New-Item -ItemType Directory -Path "${{ github.workspace }}/ExternalData/" -ErrorAction SilentlyContinue }
          $selectedItems | Export-Csv -Path ${{ github.workspace }}/ExternalData/$csvFilePath -Force
          
      - name: Commit updated CSV to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update VPN server data CSV
