name: Pull external data source Sentinel prices

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  pull-sentinel-prices:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Fetch Microsoft Sentinel Prices and create CSV
        shell: pwsh
        run: |
          $apiUrl = "https://prices.azure.com/api/retail/prices?currencyCode=GBP&`$filter=productName eq 'Sentinel'" # and (location eq 'UK South' or location eq 'UK West')"
          $response = Invoke-RestMethod -Uri $apiUrl -Method Get
          $items = $response.Items
          $sortedItems = $items | Sort-Object location, skuName
          $selectedItems = $sortedItems | Select-Object skuName, unitOfMeasure, type, retailPrice, unitPrice, currencyCode, location, effectiveStartDate, meterId, meterName, skuId, productName, serviceFamily
          
          $csvFilePath = "UKSentinelPrices.csv"
          $jsonFilePath = "UKSentinelPrices.json"
          
          $externalDataPath = "${{ github.workspace }}/ExternalData/"
          if (-not (Test-Path -Path $externalDataPath)) { 
              New-Item -ItemType Directory -Path $externalDataPath -ErrorAction SilentlyContinue 
          }
          
          $selectedItems | Export-Csv -Path "$externalDataPath$csvFilePath" -Force
          
          $jsonContent = $selectedItems | ConvertTo-Json -Depth 99
          $jsonContent | Out-File -FilePath "$externalDataPath$jsonFilePath" -Force 
          
      - name: Commit updated CSV to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Microsoft Sentinel Prices CSV
