name: Pull external data source TOR Exit Nodes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  pull-external-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Pull external data and modify if needed
        shell: pwsh
        run: |
          $torExitNodesUrl = "https://check.torproject.org/torbulkexitlist"
          $outputCsvPath = "${{ github.workspace }}/ExternalData/TorExitNodes.csv"
          
          $response = Invoke-WebRequest -Uri $torExitNodesUrl
          if ($response.StatusCode -eq 200) {
          
              $content = $response.Content
              $contentString = [System.Text.Encoding]::UTF8.GetString($content)
              $exitNodeIPs = @()
              
              $lines = $contentString -split "`n"

              foreach ($line in $lines) {
                  if ($line.Trim() -ne "") {
                      # Add the IP address to the array
                      $exitNodeIPs += [PSCustomObject]@{
                          TorExitnodes = $line.Trim()  # Renamed column here
                      }
                  }
              }
          
              # Output the array to a CSV file
              if ($exitNodeIPs.Count -gt 0) {
                  $exitNodeIPs | Export-Csv -Path $outputCsvPath -NoTypeInformation
                  Write-Output "TOR exit nodes have been saved to $outputCsvPath"
              } else {
                  Write-Error "No IP addresses were found."
              }
          } 

      - name: Commit updated data to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update TOR exit nodes"
          file_pattern: ExternalData/TorExitNodes.csv
