name: Pull external data source TOR Exit Nodes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  pull-external-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Pull external data and modify if needed
        shell: pwsh
        run: |
          $torExitNodesUrl = "https://check.torproject.org/torbulkexitlist"
          $outputJsonPath = "${{ github.workspace }}/ExternalData/TorExitNodes.json"
          
          try {
              $response = Invoke-WebRequest -Uri $torExitNodesUrl
              if ($response.StatusCode -eq 200) {
                  $content = [System.Text.Encoding]::UTF8.GetString($response.Content)
                  $exitNodeIPs = @()
              
                  foreach ($line in $content -split "`n") {
                      if ($line.Trim() -ne "") {
                          $exitNodeIPs += $line.Trim()
                      }
                  }
              
                  $customObject = [PSCustomObject]@{
                      TorExitNodes = $exitNodeIPs
                  }

                  $jsonContent = $customObject | ConvertTo-Json
                  Set-Content -Path $outputJsonPath -Value $jsonContent -Force -Encoding UTF8
                  Write-Output "TOR exit nodes have been saved to $outputJsonPath"
              } else {
                  Write-Error "Failed to fetch the TOR exit nodes. Status code: $($response.StatusCode)"
              }
          } catch {
              Write-Error "An error occurred while fetching the TOR exit nodes: $_"
          }

      - name: Commit updated data to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update TOR exit nodes"
          file_pattern: ExternalData/TorExitNodes.csv
