name: Pull external data source TOR Exit Nodes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  pull-external-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Pull external data and modify if needed
        shell: pwsh
        run: |
          $torExitNodesUrl = "https://check.torproject.org/torbulkexitlist"
          
          $response = Invoke-WebRequest -Uri $torExitNodesUrl
          if ($response.StatusCode -eq 200) {
              $content = [System.Text.Encoding]::UTF8.GetString($response.Content)
              $exitNodeIPs = @()
          
              foreach ($line in $content -split "`n") {
                  if ($line.Trim() -ne "") {
                      $exitNodeIPs += [PSCustomObject]@{ TorExitNodes = $line.Trim() }
                  }
              }
          
              if ($exitNodeIPs.Count -gt 0) {
                  $csvContent = "TorExitNodes`n" + ($exitNodeIPs | ForEach-Object { $_.TorExitNodes }) -join "`n"
                  $csvPath = "${{ github.workspace }}/ExternalData/TorExitNodes.csv"
                  Set-Content -Path $csvPath -Value $csvContent -Force
                  Write-Output "TOR exit nodes have been saved to $csvPath"
              } else {
                  Write-Error "No IP addresses were found."
              }
          } else {
              Write-Error "Failed to fetch the TOR exit nodes. Status code: $($response.StatusCode)"
          }

      - name: Commit updated data to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update TOR exit nodes"
          file_pattern: ExternalData/TorExitNodes.csv
